#pragma once

void run_test_charger_app_cmd_tests(void);
void run_test_charger_session_math_tests(void);
void run_test_charger_unit_other_tests(void);
void run_test_charger_uiux_handler_tests(void);
void run_test_charger_manager_tests(void);
void run_test_charger_hardware_control_tests(void);

void run_test_app_main_tests(void);
void run_test_nvs_helpers_tests(void);
void run_test_energy_time_utils_tests(void);
void run_test_time_sync_tests(void);
void run_test_power_topology_delegate_tests(void);
void run_test_power_topology_delegate_header_tests(void);
void run_test_energy_evse_mode_tests(void);
void run_test_esp32_device_instance_info_provider_tests(void);
void run_test_charging_targets_mem_mgr_tests(void);
void run_test_charger_manager_header_tests(void);
void run_test_matter_manager_tests(void);
void run_test_matter_manager_header_tests(void);
void run_test_dem_manufacturer_delegate_header_tests(void);
void run_test_device_energy_management_delegate_impl_tests(void);
void run_test_energy_evse_delegate_impl_tests(void);
void run_test_energy_evse_delegate_impl_header_tests(void);
void run_test_energy_evse_targets_store_tests(void);
void run_test_evse_targets_store_roundtrip_tests(void);
void run_test_tlv_roundtrip_tests(void);
void run_test_electrical_power_measurement_delegate_tests(void);
void run_test_electrical_power_measurement_delegate_header_tests(void);
